from pygments.style import Style
from pygments.token import (
    Comment,
    Error,
    Generic,
    Keyword,
    Literal,
    Name,
    Number,
    Operator,
    Punctuation,
    String,
    Text,
)


class DarkerModernStyle(Style):
    name = "darker-modern"
    background_color = "#080808"
    highlight_color = "#2b2b2b"
    line_number_color = "#6e7681"
    line_number_background_color = "#080808"
    line_number_special_color = "#cccccc"
    line_number_special_background_color = "#181818"

    styles = {
        Text: "#eeffff",
        Comment: "#6A9955",
        Comment.Preproc: "#569cd6",
        Comment.Special: "#d7ba7d",
        Keyword: "#569cd6",
        Keyword.Constant: "#569cd6",
        Keyword.Declaration: "#569cd6",
        Keyword.Namespace: "#569cd6",
        Keyword.Pseudo: "#569cd6",
        Keyword.Reserved: "#C586C0",
        Keyword.Type: "#4EC9B0",
        Operator: "#d4d4d4",
        Operator.Word: "#569cd6",
        Punctuation: "#d4d4d4",
        Name: "#9CDCFE",
        Name.Attribute: "#9CDCFE",
        Name.Builtin: "#569cd6",
        Name.Builtin.Pseudo: "#569cd6",
        Name.Class: "#4EC9B0",
        Name.Constant: "#4FC1FF",
        Name.Decorator: "#DCDCAA",
        Name.Entity: "#569cd6",
        Name.Exception: "#4EC9B0",
        Name.Function: "#DCDCAA",
        Name.Label: "#C8C8C8",
        Name.Namespace: "#4EC9B0",
        Name.Tag: "#569cd6",
        Name.Variable: "#9CDCFE",
        Name.Variable.Class: "#9CDCFE",
        Name.Variable.Global: "#9CDCFE",
        Name.Variable.Instance: "#9CDCFE",
        Literal: "#ce9178",
        Literal.Date: "#b5cea8",
        String: "#ce9178",
        String.Affix: "#569cd6",
        String.Backtick: "#ce9178",
        String.Char: "#ce9178",
        String.Delimiter: "#ce9178",
        String.Doc: "#ce9178",
        String.Double: "#ce9178",
        String.Escape: "#d7ba7d",
        String.Heredoc: "#ce9178",
        String.Interpol: "#569cd6",
        String.Other: "#ce9178",
        String.Regex: "#d16969",
        String.Single: "#ce9178",
        String.Symbol: "#ce9178",
        Number: "#b5cea8",
        Number.Bin: "#b5cea8",
        Number.Float: "#b5cea8",
        Number.Hex: "#b5cea8",
        Number.Integer: "#b5cea8",
        Number.Oct: "#b5cea8",
        Generic.Deleted: "#f85149",
        Generic.Emph: "italic",
        Generic.Error: "#f85149",
        Generic.Heading: "#569cd6 bold",
        Generic.Inserted: "#2ea043",
        Generic.Output: "#eeffff",
        Generic.Prompt: "#6e7681",
        Generic.Strong: "bold",
        Generic.Subheading: "#569cd6 bold",
        Generic.Traceback: "#f85149",
        Error: "#f85149 bg:#3c1f1e",
    }
